### Server ###
server:
  port: 9999

### Spring ###
spring:

  ### Application ###
  application:
    name: config-server

  ### Profile ###
  config:
    activate:
      on-profile: default

  ### Security ###
  security:
    user:
      name: user
      password: 1111

  ### Cloud ###
  cloud:

    ### Config ###
    config:
      ### Discovery ###
      discovery:
        enabled: true
        service-id: config-server
      ### Server ###
      server:
        git:
          force-pull: true
          clone-on-start: true
          search-paths: /src/main/resources
          uri: https://github.com/spring-cloud-portfolio/config-server-repository.git

  ### Banner ###
  banner:
    location: banner/banner-3-d.txt

### Eureka ###
eureka:
  client:
    service-url:
      defaultZone: "http://user:1111@localhost:8761/eureka/"

### Logging ###
logging:
  level:
    root: info
