### Server ###
server:
  port: 9999

### Spring ###
spring:

  ### Application ###
  application:
    name: config-server

  ### Profile ###
  config:
    activate:
      on-profile: default

  ### Security ###
  security:
    user:
      name: user
      password: 1111

  ### Cloud ###
  cloud:

    ### Config server ###
    config:
      server:
        git:
          force-pull: true
          clone-on-start: true
          search-paths: /src/main/resources
          uri: https://github.com/spring-cloud-portfolio/config-server-repository.git
